# Generated by Django 4.2.4 on 2023-09-06 03:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myblog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name": "Пост", "verbose_name_plural": "Посты"},
        ),
        migrations.AlterField(
            model_name="post",
            name="publish_date",
            field=models.DateField(
                default=datetime.datetime.now, verbose_name="Дата публикации"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="text",
            field=models.TextField(verbose_name="Текст записи"),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=250, verbose_name="Заголовок записи"),
        ),
        migrations.AlterField(
            model_name="post",
            name="update_date",
            field=models.DateField(auto_now=True, verbose_name="Дата обновления"),
        ),
    ]
